### ISSUE TITLE
[Question] 6-letter captchas

### ISSUE THREAD

**Issue by fresm** [wegeneredv-de/CaptchaSolver#1]
I've tried your CaptchaSolver on 6-letter captchas with a little more obfuscation:

![captcha](https://user-images.githubusercontent.com/35149775/37285323-01dd6890-25ff-11e8-91ea-a20bdad69372.jpeg)

Sadly extract_single_letters_from_captchas.py produces 75 % wrong letters - do I have to change the script to cope with 1/6 length compared to 1/4?

**Comment by BenjaminWegener** [comment]
shouldn't be to hard, you just have to change 4 to 6 letters.
-> won't fix
